//! Detailed context-window usage breakdown shown in the input-area tooltip.
//!
//! The small ring indicator next to the input only conveys a single ratio.
//! This component provides the richer breakdown that appears when hovering the
//! ring: a single horizontal bar whose colored segments represent the token
//! categories of the last API request, the used/total token counts, and a
//! legend mapping each color to its category.

use gpui::{Hsla, div, prelude::*, px, relative};
use gpui_component::ActiveTheme;

/// Token usage of the last API request, plus the model's context limit.
///
/// The individual token categories are rendered as colored segments of a
/// single bar, sized relative to the context `limit`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ContextUsage {
    /// Fresh (uncached) input tokens.
    pub input_tokens: u32,
    /// Tokens written to the prompt cache (cache creation).
    pub cache_write_tokens: u32,
    /// Tokens read from the prompt cache.
    pub cache_read_tokens: u32,
    /// Tokens generated by the model.
    pub output_tokens: u32,
    /// The model's context token limit (0 if unknown).
    pub limit: u32,
}

impl ContextUsage {
    /// Sum of all token categories displayed in the breakdown.
    pub fn total(&self) -> u32 {
        self.input_tokens
            .saturating_add(self.cache_write_tokens)
            .saturating_add(self.cache_read_tokens)
            .saturating_add(self.output_tokens)
    }

    /// Fraction of the context window occupied by the last API request.
    ///
    /// All token categories count towards the occupancy: input and cache-write
    /// tokens are both part of the prompt, cache-read tokens were replayed from
    /// the cache into the prompt, and the output tokens of the last request
    /// become part of the prompt on the next request. This is the same total
    /// the breakdown bar visualizes, so the ring and the bar stay in sync.
    pub fn context_ratio(&self) -> Option<f32> {
        if self.limit == 0 {
            return None;
        }
        let used = self.total();
        if used == 0 {
            return None;
        }
        Some(used as f32 / self.limit as f32)
    }
}

// Fixed, theme-independent colors for the four token categories so the legend
// and bar remain readable and distinct across light and dark themes.
fn color_input() -> Hsla {
    gpui::hsla(217.0 / 360.0, 0.85, 0.58, 1.0)
}
fn color_cache_write() -> Hsla {
    gpui::hsla(28.0 / 360.0, 0.88, 0.55, 1.0)
}
fn color_cache_read() -> Hsla {
    gpui::hsla(158.0 / 360.0, 0.55, 0.48, 1.0)
}
fn color_output() -> Hsla {
    gpui::hsla(268.0 / 360.0, 0.55, 0.62, 1.0)
}

/// Format a token count compactly, e.g. `950`, `72.4k`, `1.2M`.
fn format_tokens(value: u32) -> String {
    let v = value as f64;
    if v < 1_000.0 {
        format!("{value}")
    } else if v < 1_000_000.0 {
        trim_zero(v / 1_000.0, "k")
    } else {
        trim_zero(v / 1_000_000.0, "M")
    }
}

fn trim_zero(value: f64, suffix: &str) -> String {
    let s = format!("{value:.1}");
    let s = s.strip_suffix(".0").map(str::to_string).unwrap_or(s);
    format!("{s}{suffix}")
}

/// A single-bar context-usage breakdown with a legend, rendered inside the
/// input-area tooltip.
#[derive(IntoElement)]
pub struct ContextBreakdown {
    usage: ContextUsage,
}

impl ContextBreakdown {
    pub fn new(usage: ContextUsage) -> Self {
        Self { usage }
    }

    fn segment(fraction: f32, color: Hsla) -> impl IntoElement {
        div()
            .h_full()
            .w(relative(fraction.clamp(0.0, 1.0)))
            .bg(color)
    }

    fn legend_row(
        color: Hsla,
        label: &'static str,
        value: u32,
        cx: &gpui::App,
    ) -> impl IntoElement {
        div()
            .flex()
            .flex_row()
            .items_center()
            .justify_between()
            .gap_4()
            .child(
                div()
                    .flex()
                    .flex_row()
                    .items_center()
                    .gap_2()
                    .child(div().size(px(8.0)).rounded_full().bg(color))
                    .child(div().text_color(cx.theme().popover_foreground).child(label)),
            )
            .child(
                div()
                    .text_color(cx.theme().muted_foreground)
                    .child(format_tokens(value)),
            )
    }
}

impl RenderOnce for ContextBreakdown {
    fn render(self, _window: &mut gpui::Window, cx: &mut gpui::App) -> impl IntoElement {
        let usage = self.usage;
        let limit = usage.limit.max(1);

        // Segment fractions relative to the full context window.
        let frac = |tokens: u32| tokens as f32 / limit as f32;

        let percent = (usage.total() as f32 / limit as f32 * 100.0).round() as u32;

        div()
            .flex()
            .flex_col()
            .gap_2()
            .w(px(240.0))
            .child(
                div()
                    .text_sm()
                    .font_weight(gpui::FontWeight::MEDIUM)
                    .text_color(cx.theme().popover_foreground)
                    .child("Context Window"),
            )
            // The bar: muted background with colored segments.
            .child(
                div()
                    .h(px(8.0))
                    .w_full()
                    .rounded_full()
                    .overflow_hidden()
                    .bg(cx.theme().muted_foreground.opacity(0.2))
                    .flex()
                    .flex_row()
                    .child(Self::segment(frac(usage.input_tokens), color_input()))
                    .child(Self::segment(
                        frac(usage.cache_write_tokens),
                        color_cache_write(),
                    ))
                    .child(Self::segment(
                        frac(usage.cache_read_tokens),
                        color_cache_read(),
                    ))
                    .child(Self::segment(frac(usage.output_tokens), color_output())),
            )
            .child(
                div()
                    .text_xs()
                    .text_color(cx.theme().muted_foreground)
                    .child(format!(
                        "{} of {} tokens ({}%)",
                        format_tokens(usage.total()),
                        format_tokens(usage.limit),
                        percent
                    )),
            )
            // Legend, keyed to the last API request.
            .child(
                div()
                    .flex()
                    .flex_col()
                    .gap_1()
                    .pt_1()
                    .text_xs()
                    .child(
                        div()
                            .text_color(cx.theme().muted_foreground)
                            .child("Last API request"),
                    )
                    .child(Self::legend_row(
                        color_input(),
                        "Input Tokens",
                        usage.input_tokens,
                        cx,
                    ))
                    .child(Self::legend_row(
                        color_cache_write(),
                        "Cache Write Input Tokens",
                        usage.cache_write_tokens,
                        cx,
                    ))
                    .child(Self::legend_row(
                        color_cache_read(),
                        "Cache Read Input Tokens",
                        usage.cache_read_tokens,
                        cx,
                    ))
                    .child(Self::legend_row(
                        color_output(),
                        "Output Tokens",
                        usage.output_tokens,
                        cx,
                    )),
            )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn format_tokens_compact() {
        assert_eq!(format_tokens(0), "0");
        assert_eq!(format_tokens(950), "950");
        assert_eq!(format_tokens(1_000), "1k");
        assert_eq!(format_tokens(72_400), "72.4k");
        assert_eq!(format_tokens(1_000_000), "1M");
        assert_eq!(format_tokens(1_200_000), "1.2M");
    }

    #[test]
    fn context_ratio_counts_all_categories() {
        let usage = ContextUsage {
            input_tokens: 10,
            cache_write_tokens: 5,
            cache_read_tokens: 30,
            output_tokens: 8,
            limit: 100,
        };
        assert_eq!(usage.total(), 53);
        assert_eq!(usage.context_ratio(), Some(0.53));
    }

    #[test]
    fn context_ratio_none_without_limit() {
        let usage = ContextUsage {
            input_tokens: 10,
            limit: 0,
            ..Default::default()
        };
        assert_eq!(usage.context_ratio(), None);
    }
}
